version: "3"

services:

    rabbitmq:
        image: rabbitmq:3-management
        container_name: ppgm-rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: "ppgm"
            RABBITMQ_DEFAULT_PASS: "ppgm"
        ports:
            - "15672:15672"
            - "5672:5672"            

    sql-server:
        image: ppgm/sql-server:latest
        container_name: ppgm-sql-server
        build: 
            context: ./sql
            dockerfile: ./Dockerfile
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "@ppgm2021"
            ACCEPT_EULA: "Y"     

    