version: "3"

services:

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbit-ppgm
        environment:
            RABBITMQ_DEFAULT_USER: "ppgm"
            RABBITMQ_DEFAULT_PASS: "ppgm"

    api-auth:
        image: ppgm/auth:latest
        container_name: ppgm-api-autenticacao
        build: 
            context: ../backend/src
            dockerfile: ./services/PPGM.Autenticacao.API/Dockerfile  
        restart: always    
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5101;http://+5102
            - ASPNETCORE_Kestrel__Certificates__Default__Password=ppgm
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ppgm-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq            

    api-usuario:
        image: ppgm/api-usuario:latest
        container_name: ppgm-api-usuario
        build: 
            context: ../backend/src
            dockerfile: ./services/PPGM.Usuarios.API/Dockerfile
        restart: always 
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5401;http://+5402
            - ASPNETCORE_Kestrel__Certificates__Default__Password=ppgm
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ppgm-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-auth
            - sql-server  