version: "3"

services:

    ppgm-web:
        image: ppgm/web:latest
        container_name: ppgm-web
        build:
            context: ../src/web/PPGM.Web/
            dockerfile: ./Dockerfile
        restart: always
        volumes: 
            - dpkeys:/var/data_protection_keys/         
        ports:
            - "8085:80"
            - "4443:443"        

    
volumes:
    dpkeys:   