version: "3"

services:

    api-bff-integracao:
        image: ppgm/api-bff-integracao:latest
        container_name: ppgm-api-bff-integracao
        build: 
            context: ../src
            dockerfile: ./api-gateways/PPGM.BFF.Integracao/Dockerfile
        restart: always 
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5901;http://+5902
            - ASPNETCORE_Kestrel__Certificates__Default__Password=ppgm
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ppgm-cert.pfx
        volumes:
            - ./certs:/https:ro
        ports:
            - "5901:5901"
            - "5902:5902"

volumes:
    dpkeys:   