version: "3"

services:

    ppgm-sql-server:
        image: ppgm/sql-server:latest
        container_name: ppgm-sql-server
        build: 
            context: ../sql/sqlserver
            dockerfile: ./Dockerfile
        environment:
            SA_PASSWORD: "@ppgm2021"
            ACCEPT_EULA: "Y"
        restart: always
        ports:
            - "1433:1433"

    ppgm-mysql:
        image: ppgm/mysql:latest
        container_name: ppgm-mysql
        build: 
            context: ../sql/mysql
            dockerfile: ./Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD: "@ppgm2021"
            # MYSQL_DATABASE: PPGM
            # MYSQL_USER: "sa"
            # MYSQL_PASSWORD: "@ppgm2021"
        restart: always
        ports: 
            - "3306:3306"
    
    ppgm-adminer:
        image: adminer:latest
        container_name: ppgm-adminer
        restart: always
        ports:
            - 9001:8080
        links:
            - ppgm-mysql

    ppgm-redis:
        image: redis:latest
        container_name: ppgm-redis
        command: redis-server --requirepass @ppgm2021
        restart: always
        ports:
            - "6379:6379"

    ppgm-redis-commander:
        container_name: ppgm-redis-commander
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: always
        environment:
            - REDIS_HOSTS=local:ppgm-redis:6379:0:@ppgm2021
        ports:
            - "8083:8081"

    ppgm-mongo:
        image: ppgm/mongo:latest
        container_name: ppgm-mongo
        build: 
            context: ../sql/mongodb
            dockerfile: ./Dockerfile
        # environment:
        #     MONGO_INITDB_ROOT_USERNAME: root
        #     MONGO_INITDB_ROOT_PASSWORD: "@ppgm2021"
        #     MONGO_INITDB_DATABASE: ppgm-db
        restart: always
        ports:
            - "27017:27017"
        # volumes:
        #     - ../sql/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    ppgm-mongo-express:
        image: mongo-express
        container_name: ppgm-mongo-express
        environment:
            ME_CONFIG_MONGODB_SERVER: ppgm-mongo
            ME_CONFIG_BASICAUTH_USERNAME: root
            ME_CONFIG_BASICAUTH_PASSWORD: ppgm2021
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: ppgm2021
        restart: always
        ports:
            - "8084:8081"
        depends_on: 
            - ppgm-mongo
