version: "3"

services:

    api-sasci:
        image: ppgm/api-sasci:latest
        container_name: ppgm-api-sasci
        build: 
            context: ../src
            dockerfile: ./services-municipio/PPGM.SASCI.API/Dockerfile
        restart: always 
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5501;http://+5502
            - ASPNETCORE_Kestrel__Certificates__Default__Password=ppgm
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ppgm-cert.pfx
        volumes:
            - ./certs:/https:ro
        ports:
            - "5501:5501"
            - "5502:5502"        

volumes:
    dpkeys:   